name: Hello World

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello"
  world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: hello

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "...World!"

  list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: world

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: ls -lah

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: world

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: test -f ./rainbow-fruit.md
        
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    environment: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: deploy test
        run: echo "Deployed!!!!"
